#! /bin/bash
# Copyright (c) 2016 UnderGrid Network Services
# All rights reserved.
#
# Author: Jeremy T. Bouse, 2016
#
# /etc/init.d/speedcomplainer
#
### BEGIN INIT INFO
# Provides: speedcomplainer
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Speed Complainer daemon process
# Description:    Runs up the speedcomplainer daemon process
### END INIT INFO

# Activate the python virtual environment
    . {{ venv_path }}/bin/activate

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    {{ venv_path }}/speedcomplainer.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    {{ venv_path }}/speedcomplainer.py stop
    ;;
  restart)
    echo "Restarting server"
    {{ venv_path }}/speedcomplainer.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/speedcomplainer {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
